### ISSUE TITLE
Wrong compilation for contextual component with curly invocation

### ISSUE THREAD

**Issue by simonihmig** [glimmerjs/glimmer-vm#1025]
With the latest Ember versions (3.18 canary / 3.17 beta) - which use the latest GlimmerVM AFAIK - I am seeing some failed addon tests for these versions (only!). The issue that made the tests fail was a contextual component being called with curly invocation, and `hasBlock` inside that component wrongly returned `true`.

This was in a test using `hbs` for inline compilation, so I was able to easily see the compilation results, which seems to be wrong:

```hbs
<BsModal as |modal|>
  {{modal.footer}}
</BsModal>
```

compiles to:

```
{"symbols":["modal"],"statements":[[7,"bs-modal",[],[[],[]],[["default"],[{"statements":[[1,1,0,0,"\\n  "],[1,0,0,0,[27,[24,1],["footer"]]],[1,1,0,0,"\\n"]],"parameters":[1]}]]]],"hasEval":false,"upvars":[]}
```

The interesting part is the opcode of `1` for the `footer` component invocation, which - if I am able to interpret those [`opcodes`](https://github.com/glimmerjs/glimmer-vm/blob/master/packages/%40glimmer/wire-format/lib/opcodes.ts)  correctly - is a simple text statement.

This still invoked the component, but `hasBlock` evaluated to `true` as stated above.

For comparison:

```hbs
<BsModal as |modal|>
  <modal.footer />
</BsModal>
```

compiles to:

```
{"symbols":["modal"],"statements":[[7,"bs-modal",[],[[],[]],[["default"],[{"statements":[[1,1,0,0,"\\n  "],[7,[27,[24,1],["footer"]],[],[[],[]],null],[1,1,0,0,"\\n"]],"parameters":[1]}]]]],"hasEval":false,"upvars":[]}
```

I would have expected this to be basically equivalent, but now the `footer` invocation has an opcode of `7` - which seems to be `DynamicComponent`. With that, everything works as expected!

**Comment by simonihmig** [comment]
FWIW, I had a very similar looking problem (`hasBlock` being wrong) when using an `embroider` build - by coincidence the very same component, but a different case (ABI). Not sure if it's really related, but posting it here nevertheless, in case it is: https://github.com/embroider-build/embroider/issues/373

**Comment by simonihmig** [comment]
Seems this is the same issue as https://github.com/emberjs/ember.js/issues/18732, and I cannot see this anymore with the latest canary build, so closing this.

**Comment by rwjblue** [comment]
Thanks for checking @simonihmig!
