### ISSUE TITLE
@glimmer/runtime HTMLElement issue

### ISSUE THREAD

**Issue by joze2016** [glimmerjs/glimmer-vm#1052]
I used @glimmer/urntime in my project, when build my project, below issue happen. could you please check this file?

node_modules/@glimmer/runtime/dist/types/lib/vm/rehydrate-builder.d.ts:41:24 - error TS2304: Cannot find name 'HTMLElement'.

41     getMarker(element: HTMLElement, guid: string): Option<SimpleNode>;

**Comment by rwjblue** [comment]
Hmm, this report doesn't really have many details.  I'd love to try to help, but the types of errors you are referring to are very dependent on your setup.

I think the best bet would be to make a demonstration repository that shows what you are running into, without that I don't think we'll be able help very much...

**Comment by locks** [comment]
Closing due to lack of details. If you can provide more details please re-open the issue!
