### ISSUE TITLE
memoizeTracked drops `this` value

### ISSUE THREAD

**Issue by speigg** [glimmerjs/glimmer-vm#1084]
When wrapping an unbound function by the function returned from `memoizeTracked`, the `this` value is always `undefined`, making it difficult to write a decorator that memoizes a class method. 

I would suggest that the function callback approach be changed from:

https://github.com/glimmerjs/glimmer-vm/blob/b38ab127230fb32f2df07f7c0260d0510a14b3d5/packages/%40glimmer/validator/lib/tracking.ts#L123

to

```js 
lastValue = callback.apply(this, args); 
```

**Comment by speigg** [comment]
@pzuraq I assume you'll want to look at this

**Comment by rwjblue** [comment]
Hmm, I think this was intentional (specifically that you would use an arrow function) :thinking:

**Comment by pzuraq** [comment]
Yeah, this is intentional. Memoization must happen per-instance, so passing in an arrow function with the correct context is just as performant as a function that maintains access to this. In fact, it's more performant, because the arrow function has `this` bound, whereas if we used `this` from the function context, we would then need to add a `WeakMap` to lookup the cache for the instance state.

If you want to memoize a method, the way you would do it with this API is:

```js

**Comment by pzuraq** [comment]
cl

**Comment by speigg** [comment]
> This is really meant to be a low-level API, and it actually won't be the final public API we exposed, we've made some changes in the RFC. We'll still use this function internally, but there could be breaking changes so I wouldn't recommend using it directly. Instead, you should wrap it with a decorator or some other higher-level function.

Yes, I am doing this now (wrapping `memoizedTracked` in a decorator), but I suppose I'm doing it the wrong way: 

```js
class Foo {
  @memo myMethod() {
    // ...
  }
}
```

To clarify, is this what you are suggesting?

```js
class Foo {
  @memo myMethod = () => { 
       //... 
   } 
}
```

**Comment by pzuraq** [comment]
You have to make a new memoized function per instance, so your decorator has to use a `WeakMap` internally:

```js
function memo(target, key, desc) {
  let memoMap = new WeakMap();
  let fn = desc.value;

  return {
    get() {
      let memoizedFn = memoMap.get(this);

      if (memoizedFn === undefined) {
        memoizedFn = memoizeTracked(fn.bind(this));
        memoMap.set(this, memoizedFn);
      }

      return memoizedFn;
    }
  }
}
```

**Comment by speigg** [comment]
That's super helpful, and exactly what I was trying to accomplish! Thanks @pzuraq!

**Comment by pzuraq** [comment]
No problem! Once the [RFC lands](https://github.com/emberjs/rfcs/pull/615/files/9333565d9cf65e61c8a53ba0dee4f889ddc4472d) and we update the public API I highly recommend switching over to that. Between it and `@tracked`, you should be able to use just the public APIs exposed from `@glimmer/tracking` and not need to dig into this lower level package.

**Comment by speigg** [comment]
@pzuraq btw, wouldn't this be more efficient than maintaining a weak map?

```js

function memo(target, key, desc) {
  let fn = desc.value;
  return {
    get() {
      const memoizedFn = memoizeTracked(fn.bind(this))
      Object.defineProperty(this, desc.key, { value: memoizeTracked })
      return memoizedFn;
    }
  }
}
```

**Comment by pzuraq** [comment]
Yes in terms of lookup speed, but it would result in a shape change the first time the function is called. This would bust any inline caching/optimization that the VM has done around the shape of the object, which in our experience tends to be a much worse performance issue in general than a slightly slower lookup speed using a map.

The alternative is to use an initializer, but this makes the function effectively a class field, which means super is broken, among other things (enumerability, etc).

Hopefully the final decorators spec will have a better alternative here, for the time being this is what I’d recommend.

**Comment by speigg** [comment]
Wow, great points. I hadn't considered the performance implications of changing the shape. You've clearly put a lot of thought into the design. Thanks again.
