### ISSUE TITLE
Inconsistent TextNode parsing following a BlockStatement

### ISSUE THREAD

**Issue by dcyriller** [glimmerjs/glimmer-vm#1137]
## Description

Playing with `@glimmer/syntax`'s `preprocess`...

Is it expected that in
```
{{#block}}{{/block}}
text
```
and 
```
{{#block}}
{{/block}}
text
```
the
```
text
```
part doesn't have the same AST?

## Issue

In the first case, node.chars is `\ntext` while in the second case it is `text`.

## handlebars.js output
Parsed with handlebars.js, the output is consistently `\ntext`.

## Links

- astexplorer.net reproduction: https://astexplorer.net/#/gist/c2719834f15a4c8efc933fad2b747283/8c514ea2e85178a94769fc92f6de05abfac25d3a

**Comment by rwjblue** [comment]
@dcyriller - Are you testing in codemod mode?

**Comment by dcyriller** [comment]
Yes, I am indeed

**Comment by dcyriller** [comment]
Indeed in codemod mode the output is the same. I got confused by astexplorer displaying the regular mode. Thank you @rwjblue!
