### ISSUE TITLE
Remove `require('url')` usage

### ISSUE THREAD

**Issue by pzuraq** [glimmerjs/glimmer-vm#1140]
We currently use `require('url')` in places where we parse the URLs to see if they're safe to execute, specifically for Node. We should replace this with the [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) API.

**Comment by zackthehuman** [comment]
It looks like there are only a few (or one?) places where this happens. I have some time to pick this up if this is a simple API swap. Are we OK with the lack of IE support?

**Comment by rwjblue** [comment]
I think that we'd fallback to the current system if `typeof URL === 'undefined'` (RE: IE support).

**Comment by rwjblue** [comment]
FYI - I ended up needing to tackle this due to the regression reported in #1141 (see #1155).
