### ISSUE TITLE
Missing <output> in attr_overrides

### ISSUE THREAD

**Issue by KrishnaRPatel** [glimmerjs/glimmer-vm#1207]
Line:
https://github.com/glimmerjs/glimmer-vm/blob/25fb030869c6e047e3c7b963399b98c8ee6bd7c4/packages/%40glimmer/runtime/lib/dom/props.ts#L48

Bug:
https://github.com/emberjs/ember.js/issues/19272

Setting an `<output>`'s `form` with a non-ancestor form's `id` should be allowed, but is set as `readonly` in typescript (as it is in the whatwg idl). `<output>`'s form attribute is similar to the others (https://github.com/whatwg/html/issues/6165) so we should add the `output` tag as an additional override here.

**Comment by rwjblue** [comment]
Fixed by #1209
