### ISSUE TITLE
Expected call head to be a string, got [32,0,["resetEditedItem"]]

### ISSUE THREAD

**Issue by lifeart** [glimmerjs/glimmer-vm#1219]
ember: 3.23.0

![image](https://user-images.githubusercontent.com/1360552/100788620-62726d80-3426-11eb-8aea-0424ca35c0e5.png)

![image](https://user-images.githubusercontent.com/1360552/100788668-774f0100-3426-11eb-81cd-7cc8fc87e936.png)

likely it's an template error `(this.resetEditedItem)` should be just `this.resetEditedItem`, but, stack trace looks scary.

**Comment by rwjblue** [comment]
Is this still an issue with ember-source's canary channel?

**Comment by lifeart** [comment]
I will check and reopen it once result is same

**Comment by lifeart** [comment]
![image](https://user-images.githubusercontent.com/1360552/105904002-a605e400-6031-11eb-84c4-30ea7eed6a0d.png)

have same error on 3.24 

for case, like `@depth={{@deph (inc (or @depth 0))}}`

**Comment by lifeart** [comment]
![image](https://user-images.githubusercontent.com/1360552/105905494-8c659c00-6033-11eb-89a2-fc9e8c421484.png)

**Comment by rwjblue** [comment]
thanks for testing!

**Comment by lifeart** [comment]
closing as old
