### ISSUE TITLE
Support HandleBars's partials in the parser for other downstream projects

### ISSUE THREAD

**Issue by Spice-King** [glimmerjs/glimmer-vm#1251]
So, I know this is not really a improvement for Glimmer it's self, but other projects use your parser for Handlebars. The official one just tokens the the Handlebars bits, leaving the HTML as text tokens. Prettier is the one I'm aware of, and it's a beta option right now. I'm kinda stuck with Handlebars unless I want to pull on a whole another templating system. I only really noticed it since I was making a pass to my templates more DRY. This is the code that would need changes.

https://github.com/glimmerjs/glimmer-vm/blob/2a8cb9642fbe8e548dffe8c462686d8b1d888fbf/packages/%40glimmer/syntax/lib/parser/handlebars-node-visitors.ts#L252

While I could write my own parser, or fork this one and change it, I'd still need to write a plugin for Prettier. It's a lot of overhead that I'd rather sink into my actual project, and it would not get the long term care like your own Glimmer parser nor Prettier it's self. I could also just use the HTML formatting in Prettier, but that would just do bad things to the Handlebars expressions as it would just be treated as text.

While I could write a PR to change the parser, I'd have no clue as to where to start to add a the checks needed to reject the consumption of the Handlebars partials out of the AST.

**Comment by lifeart** [comment]
@Spice-King parser version 1 has partials support

**Comment by Spice-King** [comment]
Sorry, missed the email. Been up to my ears with a fire at work.

I was unaware that v1 had it, so I'll look at seeing about getting it downgraded and functional in Prettier.

**Comment by Spice-King** [comment]
Well, I found the last version that had it, v0.21.2, a version just about 4 years old at this point. https://github.com/glimmerjs/glimmer-vm/commit/d3366bc17f12077e2778db5adebd695e004fc209 is the commit that adds code to throw instead, and is included in v0.22.0 and forward.

I don't think it would even be viable to try and suggest to use it to the Prettier team. I'll probably try to glue togeather a solution for my self.

**Comment by lifeart** [comment]
@Spice-King glimmer-handlebars, is quite different, comparing to classic handlebars, for example: https://github.com/glimmerjs/glimmer-vm/issues/1233

best way - use handlebars parser, see https://astexplorer.net/#/gist/3cb842b638ab70885275d4f5ece071a6/049f79c9d6825d4df2a0fb8f39b8ba2f1264a34f

**Comment by rwjblue** [comment]
FWIW, I think it could be fine to move those errors to the compiler instead of the parser. That would make it parse properly, but not impact anything on the Ember / Glimmer.js side of things.

**Comment by lifeart** [comment]
@rwjblue there is no support for 

```hbs
<div {{#if this.foo}} bar {{/if}} class="body"></div>
```

**Comment by rwjblue** [comment]
@lifeart sure, but that has nothing to do with partials (which AFAICT is what this issue is about)
