### ISSUE TITLE
Reformatting breaks certain HTML entities

### ISSUE THREAD

**Issue by jpike88** [glimmerjs/glimmer-vm#1283]
I use the VSCode extension ```handlebars-formatter``` (https://github.com/mfeckie/handlebars-formatter) which relies on prettier (https://github.com/prettier/prettier) which in turn relies on glimmer.

I tried to format this:

```
<span class="stampFont" style="font-family: 'stampfont'">&#xf000;</span>
```

That entity is valid HTML and shouldn't be stripped... but it gets changed to this:

```
<span class="stampFont" style="font-family: 'stampfont'">
  
</span>
```

**Comment by jpike88** [comment]
https://github.com/prettier/prettier/issues/10542#issuecomment-799477463

**Comment by pzuraq** [comment]
Definitely would be open to a fix, unsure exactly where this would be transforming in the system itself, likely when we first read the text node's content?

**Comment by rwjblue** [comment]
@jpike88 - We explicitly provide modes that disable entity parsing, seems like they should be leveraging that?

**Comment by rwjblue** [comment]
See https://github.com/glimmerjs/glimmer-vm/pull/938

**Comment by thorn0** [comment]
Prettier uses that setting. Named entities are preserved, numeric character reference aren't.

**Comment by jpike88** [comment]
This use case is because I have large custom font libraries consisting of symbols.

**Comment by rwjblue** [comment]
Thank you! I believe that https://github.com/glimmerjs/glimmer-vm/pull/1284 will fix this (added your snippet as a test case to confirm).

**Comment by rwjblue** [comment]
Released in https://github.com/glimmerjs/glimmer-vm/releases/tag/v0.77.2

**Comment by jpike88** [comment]
cheers!
