### ISSUE TITLE
Feature flag for default helper manager

### ISSUE THREAD

**Issue by chancancode** [glimmerjs/glimmer-vm#1383]
We landed support for default helper manager in #1348. However, we forgot to include a way to turn the feature off. This is needed because every new feature landing in Ember need to be flagged. The general idea is:

1. In here, we need to add a boolean flag for the feature (either directly on the interface, or nested under `features` or something). please the export: https://github.com/glimmerjs/glimmer-vm/blob/e00baec72b4de60487a290265c818cb53bfb9c35/packages/%40glimmer/global-context/index.ts#L138

2. Then in the new code introduced in #1348, we can add a conditional that import and checks that flag prior to returning the default helper manager.

3. Then we will add an Ember feature flag on the Ember side, and reference it in here: https://github.com/emberjs/ember.js/blob/f89dd90290e993ce8bc9ea5f7f103a82687a2be9/packages/%40ember/-internals/glimmer/lib/environment.ts#L21

4. Release these as 0.84.1 and tweak https://github.com/emberjs/ember.js/pull/20013 accordingly

cc @wagenet @NullVoxPopuli (though I don't think either one of them has the time to do it, so feel free to pick this up)

**Comment by locks** [comment]
@chancancode do you know of a feature flag example in glimmer-vm that a contributor could base themselves on?
