### ISSUE TITLE
expose visitor keys in index

### ISSUE THREAD

**Issue by patricklx** [glimmerjs/glimmer-vm#1436]
So we can import them normally.
Now i have to do something like this: 
https://github.com/ember-cli/eslint-plugin-ember/blob/050185cec885f087c0fb27f2efce04d949f428f1/lib/parsers/gjs-parser.js#L6

**Comment by NullVoxPopuli** [comment]
why do we need them?
Also, why is it still  using the v1 AST?

**Comment by patricklx** [comment]
How do i get the a v1 ast when using the preprocess function?

**Comment by patricklx** [comment]
And it like other functions like traverse and vistor template locals are using v1ast

**Comment by patricklx** [comment]
fixed by #1467
