### ISSUE TITLE
License metadata for v0.85 packages is missing

### ISSUE THREAD

**Issue by davidtaylorhq** [glimmerjs/glimmer-vm#1463]
We use [licensee](https://www.npmjs.com/package/licensee) to check license compatibility of all our dependencies in Discourse. The recent `0.85` version bump of glimmer packages is causing [licensee checks to fail](https://github.com/discourse/discourse/pull/24085) on `@glimmer/syntax` and `@glimmer/interfaces` because it is unable to find valid version Metadata.

This is also evident on NPM, where [v0.84.3](https://www.npmjs.com/package/@glimmer/syntax/v/0.84.3) correctly shows "License: MIT", while [v0.85.3](https://www.npmjs.com/package/@glimmer/syntax/v/0.85.3) shows "License: none".

I'm not sure what has changed here. It doesn't look like [the 0.84.3 package.json](https://github.com/glimmerjs/glimmer-vm/blame/v0.84.3/packages/%40glimmer/syntax/package.json) files had a `license` key either... so something (related to the release process?) must have been magically inserting the license metadata in the past. 🤔

**Comment by NullVoxPopuli** [comment]
Thanks for opening this issue! Che vm repo has had a toon of infra changes since 0.84.3, so that's probably an explanation.. 

Will fix, thanks!

**Comment by andreyfel** [comment]
Experiencing the same issue. Maybe an easy fix for that could be to add a `license` field to all packages' package.json files?

**Comment by NullVoxPopuli** [comment]
sounds reasonable to me! sorry I haven't gotten to this. doing too many things :sweat_smile:

**Comment by andreyfel** [comment]
https://github.com/glimmerjs/glimmer-vm/pull/1579
