### ISSUE TITLE
Expose `voidMap` and `visitorKeys`

### ISSUE THREAD

**Issue by fisker** [glimmerjs/glimmer-vm#1465]
Prettier is using them

https://github.com/prettier/prettier/blob/e682577c08e83c0ab272fc73ad1633883ad5d1a5/src/language-handlebars/visitor-keys.evaluate.js#L1
https://github.com/prettier/prettier/blob/e682577c08e83c0ab272fc73ad1633883ad5d1a5/src/language-handlebars/html-void-elements.evaluate.js#L1

These sub paths are removed in v0.85, can we export them?

**Comment by NullVoxPopuli** [comment]
looks like they may still be available from `@glimmer/syntax`, just here:

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM51TArgMx3HKCEOAcgAEBzAG1BAFMoB6VATwDsZkAPUgbgBQAzLhwA6AIIBlACoA3AIxi5wVMBjQA0vVaogA

**Comment by fisker** [comment]
We also need `voidMap`

**Comment by fisker** [comment]
Or an array of void element tags, even better.

**Comment by NullVoxPopuli** [comment]
you're right! added. thanks!
