### ISSUE TITLE
SVG element parsing regression for svg element tag names with camelCase: `ReferenceError: radialGradient is not defined` when converting to gts-component

### ISSUE THREAD

**Issue by johanrd** [glimmerjs/glimmer-vm#1550]
I get a regression when converting a template-only-hbs-component into a template-only-gts-component.

The gts-parser seems to think that the [svg element radialGradient ](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/radialGradient)is a glimmer component, and not an svg element:

### Error in browser console:
```console
radial-gradient-reproduction.ts:1 Uncaught (in promise) ReferenceError: radialGradient is not defined
  at Object.scope (radial-gradient.ts:1:956)
  at meta (opcode-compiler.js:632:1)
```

### Reproduction:

```js
// radial-gradient-reproduction.gts:

const RadialGradientReproduction = <template>
  <svg viewBox="0 0 10 10" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
      <radialGradient id="myGradient">
        <stop offset="10%" stop-color="gold" />
        <stop offset="95%" stop-color="red" />
      </radialGradient>
    </defs>
    <circle cx="5" cy="5" r="4" fill="url('#myGradient')" />
  </svg>
</template>;

export default RadialGradientReproduction;
```
### Environment:
```json
"@glimmer/component": "^1.1.2",
"@embroider/compat": "3.4.3",
"@embroider/core": "3.4.3",
"@embroider/router": "2.1.6",
"@embroider/webpack": "3.2.1",
"ember-template-imports": "^4.0.0",
"ember-source": "5.5.0",
```

**Comment by NullVoxPopuli** [comment]
Do you happen to have what the compiled version of that component looks like?

**Comment by johanrd** [comment]
@NullVoxPopuli like this, you mean?

radial-gradient-reproduction.ts:
```ts
import { template } from "@ember/template-compiler";
const RadialGradientReproduction = template(`
  <svg viewBox="0 0 10 10" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
      <radialGradient id="myGradient">
        <stop offset="10%" stop-color="gold" />
        <stop offset="95%" stop-color="red" />
      </radialGradient>
    </defs>
    <circle cx="5" cy="5" r="4" fill="url('#myGradient')" />
  </svg>
`, {
    eval () {
        return eval(arguments[0]);
    }
});
export default RadialGradientReproduction;
```

**Comment by johanrd** [comment]
btw, this also seems to be an issue with all elements with camelCasing in svgs:
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/textPath
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateMotion
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateTransform
etc.

**Comment by NullVoxPopuli** [comment]
repro: https://limber.glimdown.com/edit?c=MQAgygag4gUDCSBnRBXApogXDAtCABogC4D2ADviGgDZoC2aAdkSAJaIgBO9JAbmgBNcIAMYBDRgHIWKRGlElG-Zq0UgSAMwLVWjNGM5ROYgayZF8cfNYDmAKw47%2BMADxF6ZamPcA%2BGCBAXRF4bfwCQXjMAdwAhEgAPAF4AIgAGEHSARizU5LCA%2BLpqRkQUgAsiIjJMAHoaqIaAOiiAZkaSThsagCZUvprgmzzwkELirHidRgBrcsrquoao5raOrsyATi2ayd1p5L8RlwE0DURDkcCp-U7jU3M2ARS6AE8jEzNmZJAbO8%2BiAAqxhKGg6dBSnBIRG8aAAFBtUgBKA75S5BUhkdQaM5oIgpACsAFJvsRyDgRCRqB0UjZKQJvjULpdAqTMZocXjkhsiSSMeTKdTktx6SBGaiAi4atcDL8PuYmYEaiczhdUS4RKxOCJaKIksl8d8RC8Cd9OCkACzfDSsajUFIoTjUWGSYCvd73ZiSZGii6SwZ%2BMJBF5EWgKwYAGhAACofJgymJELDBoiQABvcUgMpoVg2CqYEDZVKEgDcqIAvoGBsHQ64au46J4YX5rJYgA&format=glimdown

**Comment by NullVoxPopuli** [comment]
This has all the tags we'd want: https://www.npmjs.com/package/html-spec-tags?activeTab=readme

**Comment by NullVoxPopuli** [comment]
or, maybe this is an issue with `getTemplateLocals` (what we use to build the scope argument in strict mode):

![image](https://github.com/glimmerjs/glimmer-vm/assets/199018/dd84ecee-949f-487a-9aec-e4b6d8553fa3)

**Comment by chancancode** [comment]
I ran into this too.

I didn't try super hard to break it, so this is not necessarily conclusive, but I added a test to the the strict mode tests and it passes:

```ts
  @test
  'camelCased SVG elements are not considered identifiers/references'() {
    // https://developer.mozilla.org/en-US/docs/Web/SVG/Element/linearGradient
    const Foo = defineComponent({}, stripTight`
      <svg viewBox="0 0 10 10">
        <defs>
          <linearGradient id="myGradient">
            <stop offset="5%" stop-color="gold" />
            <stop offset="95%" stop-color="red" />
          </linearGradient>
        </defs>

        <circle cx="5" cy="5" r="4" fill="url('#myGradient')" />
      </svg>
    `);

    this.renderComponent(Foo);
    this.assertHTML(stripTight`
      <svg viewBox="0 0 10 10">
        <defs>
          <linearGradient id="myGradient">
            <stop offset="5%" stop-color="gold" />
            <stop offset="95%" stop-color="red" />
          </linearGradient>
        </defs>

        <circle cx="5" cy="5" r="4" fill="url('#myGradient')" />
      </svg>
    `);
    this.assertStableRerender();
  }
```

So that matches my suspicion that the problem is not, strictly speaking, in glimmer-vm. I think the problem is likely that [babel-plugin-ember-template-compilation](https://github.com/emberjs/babel-plugin-ember-template-compilation) is using `getTemplateLocals()` and that function is no good and fundamentally unsound.

**Comment by chancancode** [comment]
While waiting for this to be fixed, I made a few template-only components for the few SVG elements that has this problem, so I can import them into `.gts` files and unblock the conversion:

<img width="1881" alt="Screen Shot 2024-03-11 at 11 49 39 PM" src="https://github.com/glimmerjs/glimmer-vm/assets/55829/574a4767-b10c-4830-a8de-e9c333e9813e">

(If you aren't using TypeScript you don't need a `.ts`/`.js` file for this)
