### ISSUE TITLE
Declare license in package.json of published packages

### ISSUE THREAD

**Issue by jelhan** [glimmerjs/glimmer-vm#1564]
The license is only declared in `package.json` at workspace root but not in the `package.json` of the published packages. Would be great if we could add it their as well as many tools rely on that information (e.g. `pnpm licenses ls`).

**Comment by jelhan** [comment]
Likely a duplicate of #1463.

**Comment by NullVoxPopuli** [comment]
A PR to improve would be most welcome!

**Comment by jelhan** [comment]
Thanks a lot @andreyfel!
