### ISSUE TITLE
Update list of allowed elements

### ISSUE THREAD

**Issue by NullVoxPopuli** [glimmerjs/glimmer-vm#1569]
Potentials lists we could use:
- https://www.npmjs.com/package/html-spec-tags?activeTab=readme

What we need:
- SVG Elements
- HTML Elements
- etc?

**Comment by NullVoxPopuli** [comment]
(or remove `getTemplateLocals` https://github.com/glimmerjs/glimmer-vm/issues/1550#issuecomment-1972012330 )

**Comment by acorncom** [comment]
@NullVoxPopuli is this still needed?

**Comment by NullVoxPopuli** [comment]
Ya

**Comment by patricklx** [comment]
babel template compilation plugin is not using getTemplateLocals anymore. so, maybe not needed? and just remove the whole list? basically, now, everything is a html element, except if it has a js local.
How does it work for non-strict mode?

https://github.com/emberjs/babel-plugin-ember-template-compilation/pull/33

**Comment by NullVoxPopuli** [comment]
We do still need to fix math elements tho:

#1593
