### ISSUE TITLE
`main` in `package.json` in 0.87.1 is `null`

### ISSUE THREAD

**Issue by boris-petrov** [glimmerjs/glimmer-vm#1571]
Which I think causes some loaders to fail.

**Comment by boris-petrov** [comment]
Sorry, my mistake, I should have used `node-linker=hoisted` instead of `shamefully-hoist=true` in pnpm's settings. All's good.

**Comment by NullVoxPopuli** [comment]
Well holup, shamefully hoist isn't a good setting. Basically makes it behave like yarn
