### ISSUE TITLE
parsing error with 0.89

### ISSUE THREAD

**Issue by patricklx** [glimmerjs/glimmer-vm#1576]
```hbs
<MyComp as | abc | >
 </MyComp>
```

Invalid block parameters syntax: expecting the tag to be closed with ">" or "/>" after parameters list:

|
|  |
|

this works:
```
```hbs
<MyComp as |abc| >
 </MyComp>
```

i think its a bit to strict on the syntax? and need improve error message

**Comment by chancancode** [comment]
Hm yea this is definitely an unintentional bug in the new parsing logic I added. Can you PR a failing test?
