### ISSUE TITLE
Inline static partials during scanning

### ISSUE THREAD

**Issue by mmun** [glimmerjs/glimmer-vm#173]
If the name of the partial is knowable during template scanning (as is the case with `{{partial "foo"}}`) we should inject the statements of the partial directly into the block the contains the partial _at scan time_. 

This will avoid creating several unnecessary opcodes that are used to track the name of the partial in the dynamic case `{{partial partialName}}` and make the performance of a static partial as if you had copy and pasted the template (plus a small, constant overhead of calling `lookupPartial`).

**Comment by GavinJoyce** [comment]
I've added [two benchmarks](https://github.com/tildeio/glimmer/pull/210) covering both the dynamic case and the static case. Unsurprisingly, they have similar timings at the moment.

I'm interested in how we might solve this and I'm also interested in possibly taking it on. I've a few questions though: 

Let's say we have the following setup:

**`simple-partial` partial:**

```hbs
<b>I'm a partial</b>
```

**data and template:**

```js
{ "partialName": "simple-partial" }
```

```hbs
<p>Static Partial: {{partial "simple-partial"}}</p>
<p>Dynamic Partial: {{partial partialName}}</p>
```

This produces the following top-level template spec:

```js
["openElement","p",[]]
["text","Static Partial: "]
["append",["helper",["partial"],["simple-partial"],null],false]
["closeElement"]
["text","\n"]
["openElement","p",[]]
["text","Dynamic Partial: "]
["append",["helper",["partial"],[["get",["partialName"]]],null],false]
["closeElement"]
["text","\n"]
```

And the following top-level render opcodes:

```ruby
OPEN-PRIMITIVE-ELEMENT("p")
TEXT("Static Partial: ")
ENTER("BEGIN [127]", "END [128]")
LABEL("BEGIN [127]")
PUT-ARGS(positional=["simple-partial"], named=<EMPTY>)
NAME-TO-PARTIAL($OPERAND)
TEST($OPERAND)
JUMP-UNLESS("END [128]")
EVALUATE-PARTIAL("simple-partial")
LABEL("END [128]")
EXIT
CLOSE-ELEMENT
TEXT("\n")
OPEN-PRIMITIVE-ELEMENT("p")
TEXT("Dynamic Partial: ")
ENTER("BEGIN [140]", "END [141]")
LABEL("BEGIN [140]")
PUT-ARGS(positional=[self.partialName], named=<EMPTY>)
NAME-TO-PARTIAL($OPERAND)
TEST($OPERAND)
JUMP-UNLESS("END [141]")
EVALUATE-PARTIAL(self.partialName)
LABEL("END [141]")
EXIT
CLOSE-ELEMENT
TEXT("\n")
```

Am I correct in thinking:

 1. The top-level template-spec will remain unchanged
 2. The top-level opcodes should be inlined and will look like:

```ruby
OPEN-PRIMITIVE-ELEMENT("p")
TEXT("Static Partial: ")
OPEN-PRIMITIVE-ELEMENT("b")
TEXT("I'm partial")
CLOSE-ELEMENT
CLOSE-ELEMENT
TEXT("\n")
OPEN-PRIMITIVE-ELEMENT("p")
TEXT("Dynamic Partial: ")
ENTER("BEGIN [134]", "END [135]")
LABEL("BEGIN [134]")
PUT-ARGS(positional=[self.partialName], named=<EMPTY>)
NAME-TO-PARTIAL($OPERAND)
TEST($OPERAND)
JUMP-UNLESS("END [135]")
EVALUATE-PARTIAL(self.partialName)
LABEL("END [135]")
EXIT
CLOSE-ELEMENT
TEXT("\n")
```

Finally, should the inlining happen somewhere in `Append.scan` or somewhere else?

**Comment by wycats** [comment]
As a general principle, the many optimizations that we already implemented or have in mind to implement are swamped by the cost of compilation. @chancancode and I have various ideas for bringing down the cost of compilation, and we should focus on that before doing additional optimizations like inlining.

(fwiw, the better opcode dsl branch is a staging ground for enabling better optimizations, but improving the infrastructure behind `refineStatement` is needed as well)

I'm eager to start work on all of that once we ship an Ember Alpha with Glimmer enabled.

**Comment by GavinJoyce** [comment]
Thanks for the context. I'll work on something else for now
