### ISSUE TITLE
`getComponentDefinition` should always receive `blockMeta`

### ISSUE THREAD

**Issue by rwjblue** [glimmerjs/glimmer-vm#287]
The `blockMeta` argument should be added to `getComponentDefinition` [here](https://github.com/tildeio/glimmer/blob/c0a92795b2df68bfed674683c2ae9c3d2b633835/packages/glimmer-runtime/lib/environment.ts#L235-L239), and threaded through the various opcodes that need it.

**Comment by locks** [comment]
Closing as no longer relevant.
