### ISSUE TITLE
glimmer branch for broccoli-ember-inline-template-compiler

### ISSUE THREAD

**Issue by stefanpenner** [glimmerjs/glimmer-vm#29]
https://github.com/rwjblue/broccoli-ember-inline-template-compiler
1. produce a standalone template compiler JS file
2. provide that tot he inline-template-compiler
3. update tests to use that.

**Comment by Turbo87** [comment]
broccoli-ember-inline-template-compiler does not seems to be maintained anymore so I'll go ahead and close this. happy to reopen if anyone feels like working on this again :)
