### ISSUE TITLE
[Regression] Initial render

### ISSUE THREAD

**Issue by chadhietala** [glimmerjs/glimmer-vm#36]
It appears at fdc0575f849 initial render has regressed some. This is pretty non-scientific (using uptime-boxes), the regression may be unavoidable but noticed the jump from 400s to 500s.

Initial render: 40db3bca5199
Mean: 468.7
SD: 9.33393
Variance: 87.12222

```
464
491
464
462
461
476
461
473
469
466
```

Initial render: 81aaa30121
Mean: 536.4
SD: 17.30896
Variance: 299.6

```
566
522
533
515
529
550
515
557
536
541
```

**Comment by chancancode** [comment]
Nice find! I'm investigating a regression that is probably related, this will help a lot.

**Comment by stefanpenner** [comment]
@chadhietala AKA perf-regressionn bot.

**Comment by chadhietala** [comment]
@stefanpenner Bro do you even bench?
<img width="1387" alt="screen shot 2016-01-19 at 8 52 45 am" src="https://cloud.githubusercontent.com/assets/183799/12432670/6fc54218-beb1-11e5-9eec-785f23d0f765.png">

**Comment by stefanpenner** [comment]
![massive](https://cloud.githubusercontent.com/assets/1377/12432732/cf99b16a-beb1-11e5-8249-d49c527f0a70.jpg)

**Comment by chancancode** [comment]
@chadhietala I think 246117e2f0ec0d2604502e26f46fec9150318fd5 and f85179e41c4c67ca940bd5fafdf98179ae946710 should have fixed the regression, can you check?

**Comment by chadhietala** [comment]
@chancancode moved in the right direction but still in 500s.

From d4a8ee32f6bca
Mean: 515.8
SD: 16.86416
Variance: 284.4
```
543
521
508
499
517
516
485
537
521
511
```

**Comment by Turbo87** [comment]
I'll go ahead and close this issue as there hasn't been any activity here for 4 years and the relevant code probably looks quite different by now 😅
