### ISSUE TITLE
Convert glimmer-syntax Walker to `class`

### ISSUE THREAD

**Issue by locks** [glimmerjs/glimmer-vm#369]
The glimmer-syntax's `Walker` class is currently using a function constructor instead of the class keyword.

Relevant code: https://github.com/tildeio/glimmer/blob/master/packages/glimmer-syntax/lib/traversal/walker.ts
Example of a class: https://github.com/tildeio/glimmer/blob/fe539562bbaf3229352214a2da645c0269c39e0f/packages/glimmer-util/lib/logger.ts#L24-L61

You can reach me or @tbieniek for help!

**Comment by ingride** [comment]
I can have a look

**Comment by simi** [comment]
I think this can be closed since [Walker](https://github.com/glimmerjs/glimmer-vm/blob/2e5df4032afe5b934f31c45b03959b117c994abb/packages/%40glimmer/syntax/lib/traversal/walker.ts#L6) is class now.

**Comment by locks** [comment]
👍
