### ISSUE TITLE
too many tag shapes

### ISSUE THREAD

**Issue by krisselden** [glimmerjs/glimmer-vm#375]
![image](https://cloud.githubusercontent.com/assets/61024/21798399/10cefa84-d6c9-11e6-916a-7d950444b92d.png)

**Comment by locks** [comment]
Is this still relevant?

**Comment by rwjblue** [comment]
Unsure, I _think_ it shouldn't be an issue now due to the monomorphic tag changes that @pzuraq did, but he should confirm

**Comment by pzuraq** [comment]
This shouldn't be an issue anymore. We can close and reopen if we notice it popping up again.
