### ISSUE TITLE
"@glimmer/syntax" on NPM is missing original TypeScript sources

### ISSUE THREAD

**Issue by Turbo87** [glimmerjs/glimmer-vm#396]
The `lib` folder and `index.ts` file are missing from the `@glimmer/syntax` package on NPM. They are explicitly mentioned in the `files` array of the `package.json` file, but apparently something else ignored them while packaging it up for publishing.

/cc @chadhietala

**Comment by krisselden** [comment]
@Turbo87 maybe a lerna publish issue? which version?

**Comment by krisselden** [comment]
I tried `npm pack` locally and it included them.

**Comment by Turbo87** [comment]
```
$ npm i @glimmer/syntax
/private/tmp
└─┬ @glimmer/syntax@0.21.2
  ├─┬ handlebars@3.0.3
  │ ├─┬ optimist@0.6.1
  │ │ ├── minimist@0.0.10
  │ │ └── wordwrap@0.0.3
  │ ├─┬ source-map@0.1.43
  │ │ └── amdefine@1.0.1
  │ └─┬ uglify-js@2.3.6
  │   ├── async@0.2.10
  │   └── optimist@0.3.7
  └── simple-html-tokenizer@0.3.0

npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

$ l node_modules/@glimmer/syntax
total 8
drwxr-xr-x  4 tbieniek  wheel   136B 22 Jan 12:08 .
drwxr-xr-x  3 tbieniek  wheel   102B 22 Jan 12:08 ..
drwxr-xr-x  4 tbieniek  wheel   136B 22 Jan 12:08 dist
-rw-r--r--  1 tbieniek  wheel   2,7K 22 Jan 12:08 package.json
```

**Comment by rwjblue** [comment]
We do not publish the raw `lib` contents AFAIK. We do now properly populate the `typings` field in the `package.json`. 

I _think_ this is the right way to do it (e.g. not publish the raw TS but publish JS + typings). Closing this for now, can reopen if y'all think I'm wrong...

**Comment by Turbo87** [comment]
wish I remembered what I was working on when I opened it... probably the AST explorer 🤔
