### ISSUE TITLE
`hasBlock`, `hasBlockParams`, etc

### ISSUE THREAD

**Issue by chancancode** [glimmerjs/glimmer-vm#41]

**Comment by mmun** [comment]
We need to support hasBlock for backwards compatibility, but we should make `(has-block ...)` a helper so that we can keep the context pure.

**Comment by chancancode** [comment]
The plan is to make the base semantics a `(has-block)` keyword with an Ember AST transform to convert the "property" form into the keyword form.

**Comment by mmun** [comment]
Excellent!

**Comment by rwjblue** [comment]
I like it!

**Comment by appwebtech** [comment]
Nice input Chan.

**Comment by Turbo87** [comment]
it seems that this has been implemented by now, so I'll go ahead and close this issue as resolved :)
