### ISSUE TITLE
stack branch TODOs

### ISSUE THREAD

**Issue by chancancode** [glimmerjs/glimmer-vm#410]
- [x] dynamic components
- [x] partials
- [x] debugger
- [x] remote elements (worm hole)
- [x] userland helpers rethink (args, more stack-based invocation)
- [x] closure helpers (`prepareArgs`)
- [x] modifiers
- [x] hooks (some are related to args proxy)
- [x] dynamic attributes (didCreateElement)
- [x] bounds (didRenderLayout)
- [x] fix stack slicing
- [x] add return?
- [ ] content deopt
- [ ] check for skipped tests?

**Comment by rwjblue** [comment]
@chadhietala / @krisselden - Did y'all fix the content deopt case?  Seems to be working properly in Ember so I am assuming it is fixed...

**Comment by chadhietala** [comment]
We did the content deopt and fixed the `todo` tests. We need to clean the tests. There are still skipped tests but don't have the in as to why they were skipped or if they can just be deleted.

**Comment by locks** [comment]
Closing due to work being finished.
