### ISSUE TITLE
Bring back {{debugger}} tests

### ISSUE THREAD

**Issue by chancancode** [glimmerjs/glimmer-vm#415]
We used to have [a full suite](https://github.com/emberjs/ember.js/pull/14869/files#diff-bde5cf3fa0fa95197a663c6140770942) of `{{debugger}}` tests in Ember that was lost when it was ported to Glimmer. We should bring them back.

**Comment by locks** [comment]
I believe https://github.com/glimmerjs/glimmer-vm/blob/master/packages/@glimmer/integration-tests/lib/suites/debugger.ts should cover this.
