### ISSUE TITLE
Optimize no-JS class case?

### ISSUE THREAD

**Issue by chancancode** [glimmerjs/glimmer-vm#45]
When registering a component without a JS class, in theory we don't need to create a component instance for it (and call hooks, etc). Probably should measure the impact before going down this path.

**Comment by sandstrom** [comment]
Can this be closed now that template-only components exist? https://github.com/emberjs/rfcs/pull/278

I'm guessing that the optimization mentioned here may already be in place?

**Comment by Turbo87** [comment]
@sandstrom I agree, this optimization has been implemented by now, so I'll go ahead and close this issue.
