### ISSUE TITLE
How do add async/await support to a glimmer app?

### ISSUE THREAD

**Issue by emil-nasso** [glimmerjs/glimmer-vm#451]
I tried out glimmer a bit yesterday. Really like what I am seeing so far. Good job! :) 👍 

I tried to do parts of the guide found here: https://glimmerjs.com/guides/tracked-properties

In that guide, async and await are used. When I try to use that I get the following error in console:

```
regeneratorRuntime is not defined
```

By some google-fu i figured out that I need some polyfills for babel. I tried to change my `ember-cli-build.js` to contain:

```js
let app = new GlimmerApp(defaults, {
    babel: {
      includePolyfill: true
    },
  });
```

But that didn't help.

Does anyone know how I can get async/await to work in a glimmer app?

(Or alternatively how to get jquery. Can I say that without being lynched?)

The "project" i'm working on is available here: https://github.com/emil-nasso/matte-app

**Comment by rwjblue** [comment]
The short answer is that you cannot do this today. We met earlier and laid out some build pipeline changes that would allow this.

**Comment by emil-nasso** [comment]
@rwjblue Ok. Great. I will await changes. Thanks for the response.

**Comment by WillsonSmith** [comment]
```
ember new test-build -b @glimmer/blueprint --web-component
```
or adding
```
@glimmer/web-component
```
to your package.json will allow you to use async/await. 

This was just added to the guides here https://github.com/migbar/glimmer-website/commit/e3a4a7889c61a860a5be7f0a540380502b8c0d46

https://glimmerjs.com/guides/tracked-properties
If you scroll down there is a note on the page about async/await.

**Comment by zooshme** [comment]
I have tried both options:

1. to add the flat --web-component when creating a new project
2. to add @glimmer/web-component to package.json 

I still get the error regeneratorRuntime is not defined. Any ideas what I could be doing wrong?

**Comment by WillsonSmith** [comment]
Looks like this has re-emerged https://github.com/glimmerjs/glimmer-website/issues/43#issuecomment-295914711

cc/ @zooshme

**Comment by locks** [comment]
Instructions now at https://github.com/glimmerjs/glimmer-application-pipeline#enabling-use-of-async-await-in-components.
