### ISSUE TITLE
Development build (especially source map) is huge

### ISSUE THREAD

**Issue by jmmk** [glimmerjs/glimmer-vm#462]
Without adding any code, the development build is 1.9 megabytes and the sourcemap is 1.5

Steps to reproduce:

- Create a new app with the blueprint: `ember new test -b @glimmer/blueprint`
- `cd test && ember build`
- `ls -lh dist/app.js` - `1.9M`

And to see how big the source map is:

- `tail -n1 dist/app.js > dist/sourcemap.js`
- `ls -lh dist/sourcemap.js` - `1.5M`

It seems unnecessary to generate such a large source map and it's likely slowing down the build a lot (the build times are much slower than what I would expect to see with Webpack for example - especially if using a cheaper source-map option). With the development server running I get ~1s for both rollup and the typescript steps for a single file change. This is not _bad_, but it is not as snappy of a refresh as I expect for an app with no code in it.

**Comment by Turbo87** [comment]
@jmmk the right repository for that issue would probably be https://github.com/glimmerjs/glimmer-application-pipeline, as that is responsible for how the apps are assembled. this repository is mainly just for the underlying rendering engine.
