### ISSUE TITLE
Investigate why removing FixThisBeforeMerge opcode breaks applications

### ISSUE THREAD

**Issue by locks** [glimmerjs/glimmer-vm#469]
From https://github.com/glimmerjs/glimmer-vm/pull/467:

> @chadhietala bisected the failure down to this commit, and we suspect that the issue is caused by the hard coding of some of the opcode id's (and removing an opcode shifted the numbers by 1). We will investigate further, but getting master into a "less broken" state is the higher priority.

**Comment by rwjblue** [comment]
Awesome, thank you for opening this!

**Comment by CvX** [comment]
`FixThisBeforeWeMerge` has been removed on Oct 11, 2017 (https://github.com/glimmerjs/glimmer-vm/commit/d4f0a35c356c6f06ad25d2e1e428c4f8af57ce15) 🙂
