### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by Turbo87** [glimmerjs/glimmer-vm#477]
From https://travis-ci.org/glimmerjs/glimmer-vm/builds it looks like the last successful CI run on Travis was on 2017-03-02 which is now over two months ago. For new contributors that makes it really hard to figure out what is going on and if their contribution works as intended. IMHO it should be 🔝 priority to fix this.

**Comment by chadhietala** [comment]
@Turbo87 Yea, I agree this has been unstable for far too long. I'm currently working to make CI green before any more work is done.

**Comment by Turbo87** [comment]
@chadhietala awesome, thank you!

**Comment by chadhietala** [comment]
@Turbo87 I'm going to keep this open until we resolved some of the tests @krisselden and I skipped, but you should CI is back to green. We are fast following with the fixes but we are now coming from a more stable place.

**Comment by chadhietala** [comment]
#483 Should close this.

**Comment by chadhietala** [comment]
@Turbo87 All the tests should be passing now. We still have some cleanup to do around the types and enforcing types.

**Comment by Turbo87** [comment]
@chadhietala thank you :)
