### ISSUE TITLE
HTML5 'readonly' attribute is not being treated the same as 'disabled' or 'required'

### ISSUE THREAD

**Issue by MelSumner** [glimmerjs/glimmer-vm#479]
Expected: the 'readonly' attribute on an input would be treated the same way as 'disabled' or 'required'
(only 'disabled' or 'required' is added to the input field)

Actual: the 'readonly' attribute is being added to the input field along with the boolean value. 
(<input type="text" readonly="true" />)

**Comment by Turbo87** [comment]
@MelSumner is this issue still relevant?

**Comment by locks** [comment]
I couldn't reproduce the original bug. Please re-open if you have a reproduction!

**Comment by MelSumner** [comment]
I haven’t tried it since then, but @rwjblue could confirm.
