### ISSUE TITLE
Custom element related Error: expected an implementation for 1

### ISSUE THREAD

**Issue by bjornharrtell** [glimmerjs/glimmer-vm#494]
Related to https://github.com/glimmerjs/glimmer-vm/issues/453

Template snippet jsbin:
http://jsbin.com/batohesuyu/edit?html,css,js,output

**Comment by rwjblue** [comment]
@bjornharrtell - Can you double check the JSBin?  http://jsbin.com/nipevewica/1/edit?html,css,js,output is a compile time syntax error for me ATM...

**Comment by bjornharrtell** [comment]
Sorry, I think I accidentally had it opened in two tabs with a faulty version saving over the good one. A new try:

http://jsbin.com/bufikoneze/edit?html,css,js,output

**Comment by bjornharrtell** [comment]
Ack.. still messed up. Hang on.

**Comment by bjornharrtell** [comment]
http://jsbin.com/batohesuyu/edit?html,css,js,output

**Comment by rwjblue** [comment]
Fixed by #529
