### ISSUE TITLE
Make `@glimmer/node` tests actually run 👿

### ISSUE THREAD

**Issue by rwjblue** [glimmerjs/glimmer-vm#508]
`bin/run-node-tests.js` does not run any tests (it globs files from the wrong path). To fix this, we need to:

* rework some build related things to actually emit `dist/tests/node/` or something
* replace odd qunit wrapper with real qunit node-land runner

**Comment by CvX** [comment]
[`bin/run-qunit.js`](https://github.com/glimmerjs/glimmer-vm/blob/6a52859900ba9aa53914bed739f90d261193b234/bin/run-qunit.js) (available as a [`test:node` script](https://github.com/glimmerjs/glimmer-vm/blob/6a52859900ba9aa53914bed739f90d261193b234/package.json#L23)) introduced in #904 does run all `dist/@glimmer/**/*-node-test.js` tests.

And [`bin/run-node-tests.js`](https://github.com/glimmerjs/glimmer-vm/blob/6a52859900ba9aa53914bed739f90d261193b234/bin/run-node-tests.js) is still there, but probably should be removed? 🤔

**Comment by rwjblue** [comment]
Ya. Agree. I’ll close this though.
