### ISSUE TITLE
Error: expected an implementation for 16

### ISSUE THREAD

**Issue by kellyselden** [glimmerjs/glimmer-vm#511]
Regarding #453

The object in the debugger is something like `[16, 'src', ...]`

Coming from https://github.com/kellyselden/ember-aframe/blob/ember-source/tests/dummy/app/templates/vr.hbs#L3

**Comment by rwjblue** [comment]
Awesome, thank you for reporting. Would you mind tweaking one of the JSBin's in the other related issues to identify the minimal reproduction?

**Comment by kellyselden** [comment]
Here she is http://jsbin.com/senajeqivo/edit?html,css,js,output

**Comment by rwjblue** [comment]
Fixed by #529
