### ISSUE TITLE
Restructure tests for browser-specific DOM-patches

### ISSUE THREAD

**Issue by chancancode** [glimmerjs/glimmer-vm#55]
I would like to restructure the tests for browser-specific DOM-patches (see bdb5512cf6c0c09a5f6e23821da3acf7dd6e91a9).

Goals:
- [x] Clearly [document](https://github.com/tildeio/glimmer/blob/bdb5512cf6c0c09a5f6e23821da3acf7dd6e91a9/packages/node_modules/glimmer-runtime/lib/dom.ts#L110-L116) the browser-specific quirks and our hax
- [ ] Good coverage for these quirks – they are hard to notice (I don't test on IE9 locally) and easy to break
- [ ] Clearly flag the hax/tests so we know what to remove when we drop support for certain browsers

Specifically:
- [ ] A QUnit module (or test file? even a folder?) for each quirk/hax
- [ ] Move the existing `innerHTMLFix` test cases to the module
- [ ] One test case for each of the affected elements (`<table>`, `<tbody>`, ...), probably DRY-ed up with a helper
- [ ] Test update as well as initial render
- [ ] Verify if we need to care about the other elements mentioned in the comment (`<style>`?)

**Comment by Turbo87** [comment]
@chancancode is this issue still relevant?

**Comment by chancancode** [comment]
mostly not, thank you!
