### ISSUE TITLE
Report MS Edge 15 Issue

### ISSUE THREAD

**Issue by rwjblue** [glimmerjs/glimmer-vm#553]
Need to research what is going on, but don't have access to MS Edge...

**Comment by rwjblue** [comment]
Would love help from someone with Edge on this. Basically:

```
git clone git@github.com:glimmerjs/glimmer-vm.git
cd glimmer-vm
yarn
ember test --server --no-launch
# open tests in MS Edge and share failing test info...
```

**Comment by rwjblue** [comment]
I've been chatting with @t-sauer in slack about this. He figured out that [this test](https://github.com/glimmerjs/glimmer-vm/blob/414f9beaf349c296a66708892d8fed86862b69a6/packages/%40glimmer/runtime/test/initial-render-test.ts#L411) is the one failing. 

He also discovered that it passes in Edge 14 but not Edge 15, and that Sauce Labs updated to Edge 15 only 3 days ago (approximately when this started failing).

At this point, I'm unsure if this is an Edge 15 bug or something we need to fix. Needs a bit more investigation...

**Comment by krisselden** [comment]
Devtools often affects inlining and JIT, so this sounds like an issue with Edge 15

**Comment by t-sauer** [comment]
Here is a small repro: https://jsfiddle.net/5oskefbg/1/
Alerts 0 when the devtools are closed, 2 when devtools are opened.

I have no idea where to submit Edge bugs though. @krisselden Any tips? :-D

**Comment by rwjblue** [comment]
In the meantime we need to detect this issue and skip that test so that CI can be green again.

**Comment by rwjblue** [comment]
We still need to report to Edge (or see if it is already reported). Seems like we need to report [over here](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/new/), but we need an MS account to report.

**Comment by t-sauer** [comment]
I've created an issue over there: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12380812/

**Comment by rwjblue** [comment]
Thank you again @t-sauer!
