### ISSUE TITLE
[Pls send halp again!] Test Porting Guide 

### ISSUE THREAD

**Issue by chadhietala** [glimmerjs/glimmer-vm#561]
**Requires** https://github.com/glimmerjs/glimmer-vm/pull/560

## Backstory
The repository originally started off as being a fork of HTMLBars and thus we inherited the test suite. While many tests have been added the test suite has grown somewhat organically over the past year and half. We have seen several test harnesses be introduced making it hard to understand exactly how to introduce new tests 😞 . Luckily we have landed on a test harness that we really like and need halp migrating the rest of the test suite to use it 🤞 😄 🤞 .

## Turning On The Bat Signal 🦇 

People from the internet, we need your halp! This effort is similar to the effort when we originally [introduced the Glimmer VM into Ember](https://github.com/emberjs/ember.js/issues/13127). At this point, the highest value you can do to help is to port the existing tests (and help reviewing these PRs). If you are familiar this the new test harness in Ember you should feel right at home 🏠 . If not, no reason to be worried, we have outlined the migration steps below.

## The Process
In general, and at the high-level, the process looks like this:

1. Pick a test file to port (will be found in `packages/@glimmer/runtime/test`)
2. Determine if you can break apart the tests into a more meaningful file
3. Import `RenderTests` and `module` from `@glimmer/test-helpers`
4. Extend the `RenderTest` creating your own subclass
   - Port each tests in the file and module
   - Make sure you follow the I-N-R-U cycle where appropriate
   - Remove duplicated tests 😬 
5. Pass the new subclass into `module` as such `module('NAME OF MODULE', MyTestClass)`
6. Remove the old test file
7. Create a PR
   - If you have collapsed or deleted test cases please leave comments in the Github issue explaining what was collapsed. This typically is done when the I-N-R-U cycle was spread across multiple test cases.

## How to write good tests

Here are a few general tips/rules that you can follow to improve the test cases.

### The "I-N-U-R" cycle

We would like each test to go through the "I-N-U-R" cycle:

1. Initial render
   
   Render the template you want to test, with the template and initial values of your choice (`this.render('<h1>Hello {{name}}</h1>', { name: 'Chad' })`) and assert the result is what you expect. ([Example](https://github.com/glimmerjs/glimmer-vm/blob/af9294247738503612b707546475a06ba4fdfa0e/packages/%40glimmer/runtime/test/initial-render-test.ts#L650-L651))
2. No-op re-render
   
   Call `this.assertStableRerender();` to assert that a no-op re-render is stable. ([Example](https://github.com/glimmerjs/glimmer-vm/blob/af9294247738503612b707546475a06ba4fdfa0e/packages/%40glimmer/runtime/test/initial-render-test.ts#L652))
3. Update(s) via mutation(s)
   
   Make some updates to the values you use in the templates and assert the result. You should also assert that the DOM nodes remain stable through the update. ([Example](https://github.com/glimmerjs/glimmer-vm/blob/af9294247738503612b707546475a06ba4fdfa0e/packages/%40glimmer/runtime/test/initial-render-test.ts#L654-L656))
   
   You should try to:
   - Break up the updates into multiple chunks (i.e. multiple `this.rerender` + assertion) if it makes sense. This increase chances of catching "clobbering" bugs where updating _some_ of the values will "blow away" another unrelated part of the template or causes other undesirable effects.
4. Reset via replacement
   
   Reset to the original starting condition by replacing all the variables. This helps to catch bugs where we caches the original value of the text node and forgot to update the cache along the way. In that case when you change it to anything other than the original value, it would work fine; but when you change it back to the original value it will short-circuit the DOM code and do nothing.

### Avoid duplicating tests

It is easy to copy a test case a few times to test slightly different variations of the same thing (e.g. `{{#if foo}}` starting with true vs false), and we have done that a lot in the existing tests.

Sometimes that's the best you can do, but there are a lot of problems with this. First it produces a large amount of tests physically in the file, making it hard to find things. Also, when someone need to add a new test, they will usually randomly pick one of the few variants, carrying over details/mistakes that doesn't make a lot of sense for the new scenario. When we fix bugs in one of the copies, we will probably forget the rest.

Usually, there are ways to avoid the duplication. For example, in the case of testing the different starting condition (`{{#if foo}}` against `true` and `false`), you can just test both starting conditions in the same test:

``` js
@test "if"() {
  this.render(`{{#if cond1}}T{{else}}F{{/if}}{{#if cond2}}T{{else}}F{{/if}}`, { cond1: true, cond2: false });`

  ... // follow the usual I-N-U-R cycle
}
```

In other cases, we have been able to define shared behaviors by extracting some shared super classes (putting the actual test cases in the super class), and configure the parts that are different in the subclass. This allows you to write the test cases once, and automatically have them run many different scenarios.

## Examples
Here is an example that shows how we have tested initial render and rehydration.
- [Migrate to new test harness](https://github.com/glimmerjs/glimmer-vm/pull/559)
- [Migrate Compile Error Tests](https://github.com/glimmerjs/glimmer-vm/pull/566)

As you can see, the earlier iterations was more difficult (we were still figuring out the shared test cases story), but the latter attempts were relatively straight forward. 

Here is a list of good starting points. If you are serious about working on one of these, you probably want to leave a comment below so that other people will know not to work on that. (If you ran out of time or encountered great difficult, please come back to "release the lock" and/or push your WIP work, so other people can pick it up!)

- [x] [Attributes Tests](https://github.com/glimmerjs/glimmer-vm/blob/master/packages/%40glimmer/runtime/test/attributes-test.ts)
- [x] [Compile Error Tests](https://github.com/glimmerjs/glimmer-vm/blob/master/packages/%40glimmer/runtime/test/compile-errors-test.ts)
     - Please looks at [these tests](https://github.com/glimmerjs/glimmer-vm/blob/af9294247738503612b707546475a06ba4fdfa0e/packages/%40glimmer/runtime/test/initial-render-test.ts#L1272) and potentially consolidate
- [x] [Debugger Tests](https://github.com/glimmerjs/glimmer-vm/blob/master/packages/%40glimmer/runtime/test/debugger-test.ts)
     - May require some conversation
- [x] [Ember Component Tests](https://github.com/glimmerjs/glimmer-vm/blob/master/packages/%40glimmer/runtime/test/ember-component-test.ts)
     - Please see https://github.com/glimmerjs/glimmer-vm/pull/580 for more details as to how to port these types of tests.
     - Breakup this file into more logical files 
- [x] [In-element tests](https://github.com/glimmerjs/glimmer-vm/blob/master/packages/%40glimmer/runtime/test/in-element-test.ts)
- [x] [Partial tests](https://github.com/glimmerjs/glimmer-vm/blob/master/packages/%40glimmer/runtime/test/partial-test.ts)
- [ ] [Style Warnings](https://github.com/glimmerjs/glimmer-vm/blob/master/packages/%40glimmer/runtime/test/style-warning-test.ts)
- [ ] [Updating Tests](https://github.com/glimmerjs/glimmer-vm/blob/master/packages/%40glimmer/runtime/test/updating-test.ts)
    - Breakup this file into more logical files
    - May require @chancancode and @wycats for comment as these are specific matrix style tests
- [x] [Initial Render Tests]()
    - These have already been ported but it would be great to break the file up into multiple files

## Reviews

Once you are ready to submit your PR (please feel free to submit WIP PRs!), please reference this issue in your PR description, so that we can review them.
## Timeframe

We want to get as many test ported as soon as possible. Ideally, we would like to have most (if not all) of the tests ported within the next week or two.

Thank you in advance for your help! :heart: :yellow_heart: :green_heart: :blue_heart: :purple_heart: 

**Thanks @chancancode for providing the Ember issue so I could copypasta from it** 🍝

**Comment by Serabe** [comment]
Starting with `Attributes Tests`

**Comment by Serabe** [comment]
#561

**Comment by Serabe** [comment]
#564 is ready for review. I'm starting with Ember components.

**Comment by chadhietala** [comment]
@Serabe Porting the Ember Components might be tricky as we need to create some abstraction for `testComponent` that runs unit under various conditions. Let me try to get something working.

**Comment by snewcomer** [comment]
me and @crodriguez1a are working on Style Attributes test.

**Comment by piotrpalek** [comment]
@chadhietala this might be slightly out of topic, but I tried to `npm i` in the main directory and had this error: ```❯ npm i
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
npm WARN deprecated lodash-node@3.10.2: This package is discontinued. Use lodash@^4.0.0.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! Linux 4.11.8-300.fc26.x86_64
npm ERR! argv "/usr/bin/node" "/home/peter/.npm-packages/bin/npm" "i"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.8
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: broccoli-typescript-compiler@next
npm ERR! notarget Valid install targets:
npm ERR! notarget 2.0.0-beta.1, 1.0.1, 1.0.0, 0.6.2, 0.6.1, 0.6.0, 0.5.0, 0.4.1, 0.4.0, 0.3.0, 0.2.1, 0.2.0, 0.1.2, 0.1.1, 0.1.0, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@glimmer/build'
npm ERR! notarget```

I was a bit confused on what I've done wrong (tried rm -rf node_modules && npm clear cache) but tried yarn after that and it worked. Might be a good heads up to anyone who encounters the same issue.

**Comment by tomdale** [comment]
@krisselden What version of broccoli-typescript-compiler should we be using?

**Comment by krisselden** [comment]
the tag is @beta I can add a next tag, though I'll probably just release since everyone who has tried it has said it worked well for them.

**Comment by tomdale** [comment]
@krisselden :+1: on a release

**Comment by rwjblue** [comment]
Agreed. Seems good to release to me also.

**Comment by piotrpalek** [comment]
Started porting `in-element-tests` related PR: #583

**Comment by sduquej** [comment]
Myself and @GavinJoyce are looking into Debugger tests

**Comment by snewcomer** [comment]
@chadhietala By and large is this issue still relevant?  If so, I can help with two of the items above.

**Comment by Turbo87** [comment]
as there hasn't been any activity here for over 2.5 years I'll go ahead and close this issue as apparently most of the todo items have been resolved by now.

if that is an incorrect assumption feel free to reopen the issue :)
