### ISSUE TITLE
Custom root elements don't work in local component templates

### ISSUE THREAD

**Issue by tomdale** [glimmerjs/glimmer-vm#565]
Thanks to recent work by @krisselden, you can now use the component's name as the root element in its template:

```handlebars
{{!-- src/ui/components/my-component/template.hbs --}}
<my-component>
  My component!
</my-component>
```

However, in Glimmer applications, this currently only works for "global" components (i.e., `src/ui/components/*`). Trying to use a custom element in a "local" component causes an exception to be thrown (note different template file path nested inside a parent):

```handlebars
{{!-- src/ui/components/my-parent-component/my-component/template.hbs --}}
<my-component>
  My component!
</my-component>
```

What's happening is:

1. In `scanLayout`, we call `hasComponentDefinition()` with the name of the component (`my-component`) but with *itself* as the referrer (`template:/app/components/parent-component/my-component`).
2. The resolver looks for `/app/components/parent-component/my-component/my-component` which doesn't exist.
3. An exception gets thrown because it can't find the named component.

I believe the root issue is that the code in `scanLayout` that handles the root element case should be using the *parent* component's specifier as the referrer, not the template its currently passing, but I may be missing something.

**Comment by krisselden** [comment]
Another way I think of wording this, the check for self invoking component should be in the parents scope not the local scope.

**Comment by tomdale** [comment]
@krisselden Yeah, that's a better way of putting it.

**Comment by locks** [comment]
Closing as no longer relevant.
