### ISSUE TITLE
beginAttributeValue is not called for dynamic mustache attribute value

### ISSUE THREAD

**Issue by initram** [glimmerjs/glimmer-vm#615]
when parsing `<img src={{some-dir/some-component x}}>` beginAttributeValue is never called. It does calls finishAttributeValue when it reaches `>` however. This results in the start location of the attribute value node to remain the default (line: 0, column: 0) which is not a valid location. (the first line is line 1)

This was discovered as the start location is not set correctly for the mustache statement, which made created an error in ember-tamplate-lint. See issue here: https://github.com/rwjblue/ember-template-lint/issues/253

**Comment by rwjblue** [comment]
Nice sleuthing! Definitely should be fixed here.
