### ISSUE TITLE
Cannot display property of frozen object

### ISSUE THREAD

**Issue by arkadiyk** [glimmerjs/glimmer-vm#632]
If I have a property like this:

```js
  user = Object.freeze({id: "123"});
``` 

And try to display it:

```handlebars
User id: {{user.id}}
```

I am getting this error:
```
tracked.ts:236 Uncaught TypeError: Cannot add property Symbol(ember-object), object is not extensible
```

**Glimmer Playground example: http://tinyurl.com/ycklxry6**
 
I am trying to use https://github.com/apollographql/apollo-client with Glimmer. But it fails because Apollo Client result set is frozen

**Comment by tomdale** [comment]
Should be fixed in https://github.com/glimmerjs/glimmer.js/pull/119
