### ISSUE TITLE
$REVISION counter could eventually reach Number.MAX_SAFE_INTEGER

### ISSUE THREAD

**Issue by jayphelps** [glimmerjs/glimmer-vm#675]
Hi folks 👋 

Playing around in the codebase and I noticed that $REVISION is a static variable that is [shared by DirtyableTags](https://github.com/glimmerjs/glimmer-vm/blob/d7dd2d8f0baf8dfea11246b8d30d3901a4e9f17a/packages/%40glimmer/reference/lib/validators.ts#L109). While perhaps not likely in practice, I assume this could eventually reach `Number.MAX_SAFE_INTEGER + 1` (9007199254740992) after that, incrementing it does nothing so presumably affected references would no longer dirty? Can someone confirm whether this is known and just assumed to be unlikely enough in practice to safely ignore?

I admit this is a probably pedantic...but I haven't a clue how many "dirties per second" is average so _just in case_. I realize 9007199254740992 is incomprehensibly huge 😝

**Comment by tomdale** [comment]
Hey @jayphelps, we had the same thought but are not too worried about this.

Conservatively, you could theoretically execute multiple mutations in one millisecond but it would be very difficult to do it in under one microsecond. So let's assume a theoretical maximum of one mutation per microsecond.

Even at that rate, which we would not expect to see in the real world, we would need to maintain that rate consistently for approximately 285 years before you would reach an integer high enough to cause an overflow. If a Glimmer app started now survives over 200 years of crashes, OS and browser updates, war and power outages, I would be very, very impressed—unfortunately, I'd probably be dead, too. 😉 

If JavaScript and/or hardware ever gets so fast that we start to break the 1op/µs barrier, we have an strategy for detecting this and falling back to a slower path. But it doesn't seem worth the overhead until we get close to even theoretically hitting the limit in our lifetimes.

**Comment by jayphelps** [comment]
Excellent 🖖
