### ISSUE TITLE
Glimmer Transform - Preserve spacing after transform

### ISSUE THREAD

**Issue by robert-j-webb** [glimmerjs/glimmer-vm#685]
I'm using the glimmer-vm to edit and then save some handlebars files for a refactoring project I'm working on. This has the unintended consequence of eating all the nice whitespace that makes the template more readable - see this for an example: [Transform eats white space](https://astexplorer.net/#/gist/4d00be97a3aabd49f71c5b841f277fcc/89a146fb7857cacab3730abc22eac717c47d8120). This also happens with component hashes: [here.](https://astexplorer.net/#/gist/8d8e812c2a1ff72e208bced65a7dc200/345ee360720deb41758e63137c5b4ba07af9baaa)

I've been trying to push new line characters and tabs at the right spot in the transform, but it gets really tricky really fast. Is there anyway to preserve whitespace after a transform? 

For reference, I'm using this code to edit and print the handlebars files:
```js
  const glimmer = require('@glimmer/syntax');
  const ast = glimmer.preprocess(file);
  glimmer.traverse(ast, {
    ElementNode(node) {
     //transorm code goes here
    },
  });
  return glimmer.print(ast);
```

**Comment by rwjblue** [comment]
You might want to look into using https://github.com/q2ebanking/ember-template-rewrite (which handles white space quite a bit better).  I don’t have a feature by feature comparison though.

**Comment by robert-j-webb** [comment]
Thank you so much @rwjblue! I was able to preserve whitespace by using that repo.
