### ISSUE TITLE
Unhelpful error message from unrelated errors

### ISSUE THREAD

**Issue by chriskrycho** [glimmerjs/glimmer-vm#755]
When an unhandled error gets thrown by the application, it can end up showing you only an error like this as the final result (from an example I just ran into in our Ember.js application):

```
Error: a glimmer transaction was begun, but one already exists. You may have a nested transaction
debugAssert — util.js:62
begin — runtime.js:6380
begin — environment.js:270
_renderRoots — renderer.js:311
_renderRootsTransaction — renderer.js:379
_revalidate — renderer.js:418
invokeWithOnError — backburner.js:283
flush — backburner.js:153
flush — backburner.js:345
end — backburner.js:455
run — backburner.js:533
_trigger — backburner.js:882
end — backburner.js:468
run — backburner.js:539
wrapped — raygun.js:49
mightThrow — jquery.js:3583
(anonymous function) — jquery.js:3651
(anonymous function) — error.js:155
runInDebug — index.js:246
onerror — error.js:148
invokeWithOnError — backburner.js:286
flush — backburner.js:153
flush — backburner.js:345
end — backburner.js:455
run — backburner.js:533
_trigger — backburner.js:882
end — backburner.js:468
run — backburner.js:539
wrapped — raygun.js:49
mightThrow — jquery.js:3583
(anonymous function) — jquery.js:3651
```

This is thrown here:

https://github.com/glimmerjs/glimmer-vm/blob/27393d1efdc18268e0b67d15ccceeb688b24957a/packages/%40glimmer/runtime/lib/environment.ts#L258

You can debug it the normal ways, and figure out what the original error was, but the error message itself should probably be clearer about indicating that it may result from other errors.

**Comment by rwjblue** [comment]
IMHO, we should (at the least) update the message to tell folks to look at the errors previously thrown.

**Comment by GavinJoyce** [comment]
How about:

`A glimmer transaction was begun, but one already exists. You may have a nested transaction, possibly caused by an earlier runtime exception. Please check your stack trace.`

**Comment by chriskrycho** [comment]
It’s certainly an improvement on what we have now.

That said, with the normal stack trace settings, I can guarantee that won’t actually help: I’ve never seen one of these that included a large enough stack trace to get back to what the actual problem was. (I think the usual stack depth for traces in production is 10?)
