### ISSUE TITLE
Export isRehydrationComment for rehydration/serialization concerns

### ISSUE THREAD

**Issue by rondale-sc** [glimmerjs/glimmer-vm#787]
While working on the rehydration story, outlined here: https://github.com/emberjs/ember.js/pull/16227, I've learned that it is important to be able to recognize when a given string has been created using the serialize element builder.  In Glimmer there is an assertion that ensures that a node must contain a known glimmer comment string which looks like: `'%+b:0%'` which I've used to make decisions in ember-cli-fastboot to determine how the application should behave.

In the Ember.js PR I rely on this comment in tests, and in ember-cli-fastboot I rely on it to change the behavior of the instance-initializer and to modify the boot process to ensure rehydrate mode is set correctly.  

Unfortunately, that means we have that magic string encoded all over many libraries.  I'd like to expose a `isRehydrationComment` function that can be used internally in glimmer-vm, but also in these other libraries so we don't have to hardcode the string and the underlying format can change as needed.

**Comment by rwjblue** [comment]
Totally agreed here. 

Perhaps it could even be `isRehydrationNode` (which even hides the fact that we use comments)...
