### ISSUE TITLE
Rehydration is adding placeholders tags to the head title tag

### ISSUE THREAD

**Issue by kiwiupover** [glimmerjs/glimmer-vm#796]
`<title><!--%+b:9%-->RV Rentals from the Most Trusted RV Owners | Outdoorsy<!--%-b:9%--></title>`

https://cl.ly/1r3h03190G3x

**Comment by rwjblue** [comment]
Discussed in chat with @kiwiupover, basically the serialization format for: 

```hbs
{{#in-element headElement}}
  <title>{{someDynamicThing}}</title>
{{/in-element}}
```

Ends up emitting something like:

```html
<title><!--%+b:9%-->Some Content<!--%-b:9%--></title>
```

And for `<title>` literally any content present is what will be the title of the tab/window.

**Comment by rwjblue** [comment]
As a test, I suggested trying:

```hbs
{{{somethingWithTitleTagIncluded}}}
```

Which _might_ force the rendering engine to emit the comment nodes around the title tag (but not inside of it). Obviously, this work around has a number of other significant trade offs but it seemed reasonable to try...

**Comment by krisselden** [comment]
rehydration in the rcdata state https://dev.w3.org/html5/spec-preview/tokenization.html#rcdata-end-tag-name-state is always going to have this issue

**Comment by CvX** [comment]
*I think the following should be prefaced with:*
<img src="https://user-images.githubusercontent.com/66961/60360543-3aced880-99dc-11e9-90d6-8ec1ad719080.png" alt="I have no idea what I’m doing dog meme" width="250">

----

As I mentioned in https://github.com/ember-fastboot/ember-cli-fastboot/issues/659#issuecomment-506753186, here’s a work-in-progress fix for invalid `<title>`, `<style>`, and `<script>` tags when used with `EXPERIMENTAL_RENDER_MODE_SERIALIZE`:

**simple-html-tokenizer**:
https://github.com/tildeio/simple-html-tokenizer/compare/master...CvX:text-content
Treats all contents of those element as text content.

**glimmer-vm**:
https://github.com/glimmerjs/glimmer-vm/compare/master...CvX:fix-rehydration
Prevents adding the rehydration comments in those elements.
