### ISSUE TITLE
Ember Integration

### ISSUE THREAD

**Issue by rwjblue** [glimmerjs/glimmer-vm#8]
- [x] Make tests runnable https://github.com/tildeio/glimmer/issues/10
- [x] Ensure ES6 output for publishing has correct imports #6 and #7 
- [x] Rename all packages from `htmlbars-*` to `glimmer-*`
- [x] Create package in Ember for `ember-glimmer` [branch here](https://github.com/emberjs/ember.js/tree/glimmer-packages)
- [x] Create feature flagged builds in Ember, swapping glimmer2 engine vs glimmer1 engine based on flag
- [ ] Ensure tests pass for Ember with and without the feature enabled

**Comment by Turbo87** [comment]
soooo... since `glimmer-vm` is used by Ember these days, I assume we can close this issue? 😅 

feel free to reopen if my assumption is wrong 😉
