### ISSUE TITLE
clear bounds on node that had it's textContent modified

### ISSUE THREAD

**Issue by snewcomer** [glimmerjs/glimmer-vm#813]
I'm seeing an error when navigating to another page after "clamping" the text of a node.

Essentially I am setting the textContent in `didInsertElement` similar to `element.textContent = words.slice(0, max)`.  However, when navigating to another page, the below method is looking for a node to remove.  That node was the elements previous text content, something similar to:

```
My text
<br><br>
Other text
```
which was clamped to
```
My text...
```

As a result, `parent.removeChild(node)` fails as the node is no longer a child of the parent.
```
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. at clear
```

https://github.com/glimmerjs/glimmer-vm/blob/9590669d0e463d131d44df35c20fe48fc40a4dfb/packages/%40glimmer/runtime/lib/bounds.ts#L80

Is there a different approach I need to take here in order for the vm to still find the node it needs to remove?

__
ember-source 3.1.2
ember-cli 3.1.2

**Comment by snewcomer** [comment]
Note:  If the text in the `.hbs` file is wrapped in an html element, Glimmer has no problem finding the DOM to update

```
<span>
My text...
</span>
```

**Comment by gossi** [comment]
I see the same error for me, not for a text-node but for an element, which I move around in the `didInsertElement` and `didRender` hooks.

-- 
ember-source 3.2.2

**Comment by gossi** [comment]
Update: I also had TextNodes (with whitespace only) which I manually removed (iterating over the parent: `element.childNodes`).

**Comment by Serabe** [comment]
This is still an issue. Any hint?

Thank you!

**Comment by rwjblue** [comment]
I think that this should only happen when the fragment itself contains html content, right?

Specifically, you wouldn't see the error with:

```hbs
My text blah blah blah blah
```

Being replaced with:

```hbs
My text...
```

**BUT** you would see the error for this content:

```hbs
My text <b>whatever</b> goes here
```

---

Is that correct?

**Comment by Serabe** [comment]
I am seeing this issue with only plain text as well.

**Comment by rwjblue** [comment]
@Serabe - Are you using `this.element.textContent = ` also?

**Comment by rwjblue** [comment]
Can you make a minimal repro (either twiddle or demo app)?

**Comment by Serabe** [comment]
Fnally we come to find the error. We followed these steps to overcome the problem:

1. Remove the template completely and render the text in `didInsertElement`.
2. For keeping FastBoot render we went one level above, and using a different component depending on whether we are on FastBoot or not.

Thank you!

**Comment by snewcomer** [comment]
Going to close this for now.  The error does make sense and perhaps is expected, but there are ways around as Sergio pointed out.
