### ISSUE TITLE
Glimmer's TS config should be at least as strict as Ember's

### ISSUE THREAD

**Issue by csantero** [glimmerjs/glimmer-vm#815]
I ran into problems importing certain glimmer packages from TypeScript files in ember.js due to ember.js having stricter TypeScript settings than glimmer-vm.

Ember's current tsconfig:
```json
    "strict": true,
    "noImplicitReturns": true,
    "allowUnreachableCode": false,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
```

Glimmer-vm's current tsconfig:
```json
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "allowUnreachableCode": false,
    "strictNullChecks": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
```

I have a fix in for `@glimmer/compiler` at #814, but this will become more of a problem as more of ember's codebase switches to TypeScript.

**Comment by rwjblue** [comment]
@krisselden - Can you review the two above configs and comment with what you think we should ultimately go with?
