### ISSUE TITLE
Glimmer converts html entities to equivalent chars during AST generation.

### ISSUE THREAD

**Issue by siva-sundar** [glimmerjs/glimmer-vm#833]
Html entities like `'&times;'`, `'&lt;'`, `'&gt;'` are converted to `×`, `<`, `>` during AST generation. This leads to a problem while during hbs transformations.

Here is the [reproduction demo](https://astexplorer.net/#/gist/f133213c2753d2854e7097312e424cbd/c282fee28c32ae67fb958f606fc6894b1b4f2951).

**Comment by siva-sundar** [comment]
@Turbo87 Thanks

**Comment by GavinJoyce** [comment]
@siva-sundar did you happen to solve this by doing the replacement after printing? If so, perhaps you could point out where that code lives? We'd like to do this in the `ember-angle-brackets-codemod` too: https://github.com/rajasegar/ember-angle-brackets-codemod/issues/48
