### ISSUE TITLE
Glimmer automatically converts single quotes to double quotes while hbs transform

### ISSUE THREAD

**Issue by siva-sundar** [glimmerjs/glimmer-vm#838]
This leads to a problem during hbs transformations.

```hbs
<div class="foo {{if condition 'bar'}}">
  baz
</div>

```

```hbs
<div class="foo {{if condition "bar"}}">
  baz
</div>

```

Reproduction: https://tinyurl.com/y9amgtuv

**Comment by rwjblue** [comment]
I believe this should be fixed by https://github.com/glimmerjs/glimmer-vm/pull/835

**Comment by Turbo87** [comment]
when you want to preserve the original formatting of the code then I would recommend to use https://github.com/ember-template-lint/ember-template-recast instead, which takes care of these sorts of things. the printer in `@glimmer/syntax` only cares about printing the *abstract* syntax tree, but not necessarily any specific formatting.
