### ISSUE TITLE
Enabling logging results in unbalanced operations

### ISSUE THREAD

**Issue by rwjblue** [glimmerjs/glimmer-vm#846]
At some point we have broken the ability to enable the internal debug logging (enabling it now seems to emit an error due to incorrect/unbalanced operations).

Does anyone have an idea of where to start digging into this?

**Comment by chiragpat** [comment]
I was messing around with this while I was working on #850. Seems like the InvokeComponentLayout used to change the stack by 2 but after this commit https://github.com/glimmerjs/glimmer-vm/commit/d4344e75b4bd10ae553608b8339d24ba52641e08#diff-7bb81772b9bff08cb2a8b4cb29f37dd5R567 it was simplified and now does not have the expected stack change.
