### ISSUE TITLE
Triple-curly template behavior differs from Handlebars

### ISSUE THREAD

**Issue by jacobq** [glimmerjs/glimmer-vm#851]
I'm not sure if this is right place to submit this, but during a discussion in the Ember Discord help channel (2018/9/19 ~14:00 GMT) it came to my attention that Glimmer seems to "fix" `<div>` elements wrapped in `<p>` elements like this:
`<p><div>Foo</div></p>` -> `<p></p><div>Foo</div><p></p>`. It doesn't do this with `<a>` or block level elements. I realize that wrapping a block element in an inline one other than an anchor is probably bad, but this behavior is still surprising. Handlebars also doesn't seem to do this. Also, the same HTML written directly in an Ember application's template does not get this treatment. 

[Repro example in the playground](https://glimmer-playground.netlify.com/?app=JTdCJTIyY29tcG9uZW50cyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJHbGltbWVyQXBwJTIyJTJDJTIydGVtcGxhdGUlMjIlM0ElN0IlMjJmaWxlTmFtZSUyMiUzQSUyMnNyYyUyRnVpJTJGY29tcG9uZW50cyUyRkdsaW1tZXJBcHAlMkZ0ZW1wbGF0ZS5oYnMlMjIlMkMlMjJzb3VyY2VUZXh0JTIyJTNBJTIyJTNDaDElM0VXb3JrcyUyMHdpdGglMjAlMjZsdCUzQmElMjZndCUzQiUzQyUyRmgxJTNFJTVDbkV4cGVjdGVkJTNBJTIwJTdCJTdCaHRtbDElN0QlN0QlM0NiciUzRSU1Q25BY3R1YWwlM0ElMjAlM0NkaXYlMjBpZCUzRCU1QyUyMndyYXBwZXIxJTVDJTIyJTIwc3R5bGUlM0QlNUMlMjJkaXNwbGF5JTNBbm9uZSU1QyUyMiUzRSU3QiU3QiU3Qmh0bWwxJTdEJTdEJTdEJTNDJTJGZGl2JTNFJTdCJTdCYWN0dWFsMSU3RCU3RCU1Q24lM0NociUzRSU1Q24lM0NoMSUzRURvZXNuJ3QlMjB3b3JrJTIwd2l0aCUyMCUyNmx0JTNCcCUyNmd0JTNCJTNDJTJGaDElM0UlNUNuRXhwZWN0ZWQlM0ElMjAlN0IlN0JodG1sMiU3RCU3RCUzQ2JyJTNFJTVDbkFjdHVhbCUzQSUyMCUzQ2RpdiUyMGlkJTNEJTVDJTIyd3JhcHBlcjIlNUMlMjIlMjBzdHlsZSUzRCU1QyUyMmRpc3BsYXklM0Fub25lJTVDJTIyJTNFJTdCJTdCJTdCaHRtbDIlN0QlN0QlN0QlM0MlMkZkaXYlM0UlN0IlN0JhY3R1YWwyJTdEJTdEJTIyJTdEJTJDJTIyY29tcG9uZW50JTIyJTNBJTdCJTIyZmlsZU5hbWUlMjIlM0ElMjJzcmMlMkZ1aSUyRmNvbXBvbmVudHMlMkZHbGltbWVyQXBwJTJGY29tcG9uZW50LnRzJTIyJTJDJTIyc291cmNlVGV4dCUyMiUzQSUyMmltcG9ydCUyMENvbXBvbmVudCUyQyUyMCU3QiUyMHRyYWNrZWQlMjAlN0QlMjBmcm9tJTIwJyU0MGdsaW1tZXIlMkZjb21wb25lbnQnJTNCJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBjbGFzcyUyMGV4dGVuZHMlMjBDb21wb25lbnQlMjAlN0IlNUNuJTIwJTIwaHRtbDElMjAlM0QlMjAnJTNDYSUzRSUzQ2RpdiUzRUZvbyUzQyUyRmRpdiUzRSUzQyUyRmElM0UnJTNCJTVDbiUyMCUyMCU0MHRyYWNrZWQlMjBhY3R1YWwxJTNCJTVDbiUyMCUyMGh0bWwyJTIwJTNEJTIwJyUzQ3AlM0UlM0NkaXYlM0VGb28lM0MlMkZkaXYlM0UlM0MlMkZwJTNFJyUzQiU1Q24lMjAlMjAlNDB0cmFja2VkJTIwYWN0dWFsMiUzQiU1Q24lMjAlMjBjb25zdHJ1Y3RvcihvcHRpb25zKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBzdXBlcihvcHRpb25zKSUzQiU1Q24lMjAlMjAlMjAlMjAlMkYlMkYlMjBOYXN0eSUyMGhhY2slMjBidXQlMjBzaG93cyUyMHBvaW50JTVDbiUyMCUyMCUyMCUyMHNldFRpbWVvdXQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwY29uc3QlMjB3cmFwcGVyMSUyMCUzRCUyMGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCd3cmFwcGVyMScpJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMHRoaXMuYWN0dWFsMSUyMCUzRCUyMHdyYXBwZXIxLmlubmVySFRNTCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBjb25zdCUyMHdyYXBwZXIyJTIwJTNEJTIwZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3dyYXBwZXIyJyklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwdGhpcy5hY3R1YWwyJTIwJTNEJTIwd3JhcHBlcjIuaW5uZXJIVE1MJTNCJTVDbiUyMCUyMCUyMCUyMCU3RCUyQyUyMDUwMCklM0IlMjAlMjAlMjAlMjAlNUNuJTIwJTIwJTdEJTVDbiU3RCUzQiU1Q24lNUNuJTIyJTdEJTdEJTVEJTJDJTIyaGVscGVycyUyMiUzQSU1QiU1RCU3RA==)

**Comment by locks** [comment]
> I realize that wrapping a block element in an inline one other than an anchor is probably bad, but this behavior is still surprising.

By [the HTML spec](http://www.w3.org/TR/html401/struct/text.html#h-9.3.1), putting a block element inside `p` is considered illegal. If you go to `about:blank` in a new browser tab and add `<p><div>Foo</div></p>` to the body, you will see that the result is `<p></p><div>Foo</div><p></p>`.

In this instance it is Glimmer that is correct, and the behaviour should be maintained.
Thank you for reporting!

**Comment by jacobq** [comment]
Thanks for explaining. Any idea why it doesn't get corrected like that when it's written statically [like this](https://glimmer-playground.netlify.com/?app=JTdCJTIyY29tcG9uZW50cyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJHbGltbWVyQXBwJTIyJTJDJTIydGVtcGxhdGUlMjIlM0ElN0IlMjJmaWxlTmFtZSUyMiUzQSUyMnNyYyUyRnVpJTJGY29tcG9uZW50cyUyRkdsaW1tZXJBcHAlMkZ0ZW1wbGF0ZS5oYnMlMjIlMkMlMjJzb3VyY2VUZXh0JTIyJTNBJTIyJTNDaDElM0VTdGF0aWMlMjB2cy4lMjBEeW5hbWljJTNDJTJGaDElM0UlNUNuU291cmNlJTNBJTIwJTdCJTdCaHRtbCU3RCU3RCUzQ2JyJTNFJTVDblN0YXRpYyUzQSUyMCUzQ2RpdiUyMGlkJTNEJTVDJTIyd3JhcHBlcjElNUMlMjIlMjBzdHlsZSUzRCU1QyUyMmRpc3BsYXklM0Fub25lJTVDJTIyJTNFJTNDcCUzRSUzQ2RpdiUzRUZvbyUzQyUyRmRpdiUzRSUzQyUyRnAlM0UlM0MlMkZkaXYlM0UlN0IlN0JhY3R1YWwxJTdEJTdEJTNDYnIlM0UlNUNuRHluYW1pYyUzQSUyMCUzQ2RpdiUyMGlkJTNEJTVDJTIyd3JhcHBlcjIlNUMlMjIlMjBzdHlsZSUzRCU1QyUyMmRpc3BsYXklM0Fub25lJTVDJTIyJTNFJTdCJTdCJTdCaHRtbCU3RCU3RCU3RCUzQyUyRmRpdiUzRSU3QiU3QmFjdHVhbDIlN0QlN0QlM0NiciUzRSUyMiU3RCUyQyUyMmNvbXBvbmVudCUyMiUzQSU3QiUyMmZpbGVOYW1lJTIyJTNBJTIyc3JjJTJGdWklMkZjb21wb25lbnRzJTJGR2xpbW1lckFwcCUyRmNvbXBvbmVudC50cyUyMiUyQyUyMnNvdXJjZVRleHQlMjIlM0ElMjJpbXBvcnQlMjBDb21wb25lbnQlMkMlMjAlN0IlMjB0cmFja2VkJTIwJTdEJTIwZnJvbSUyMCclNDBnbGltbWVyJTJGY29tcG9uZW50JyUzQiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwY2xhc3MlMjBleHRlbmRzJTIwQ29tcG9uZW50JTIwJTdCJTVDbiUyMCUyMCU0MHRyYWNrZWQlMjBhY3R1YWwxJTNCJTVDbiUyMCUyMCU0MHRyYWNrZWQlMjBhY3R1YWwyJTNCJTVDbiUyMCUyMGh0bWwlMjAlM0QlMjAnJTNDcCUzRSUzQ2RpdiUzRUZvbyUzQyUyRmRpdiUzRSUzQyUyRnAlM0UnJTNCJTVDbiUyMCUyMGNvbnN0cnVjdG9yKG9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHN1cGVyKG9wdGlvbnMpJTNCJTVDbiUyMCUyMCUyMCUyMCUyRiUyRiUyME5hc3R5JTIwaGFjayUyMGJ1dCUyMHNob3dzJTIwcG9pbnQlNUNuJTIwJTIwJTIwJTIwc2V0VGltZW91dCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBjb25zdCUyMHdyYXBwZXIxJTIwJTNEJTIwZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3dyYXBwZXIxJyklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwdGhpcy5hY3R1YWwxJTIwJTNEJTIwd3JhcHBlcjEuaW5uZXJIVE1MJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMGNvbnN0JTIwd3JhcHBlcjIlMjAlM0QlMjBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnd3JhcHBlcjInKSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjB0aGlzLmFjdHVhbDIlMjAlM0QlMjB3cmFwcGVyMi5pbm5lckhUTUwlM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTJDJTIwNTAwKSUzQiUyMCUyMCUyMCUyMCU1Q24lMjAlMjAlN0QlNUNuJTdEJTNCJTVDbiU1Q24lMjIlN0QlN0QlNUQlMkMlMjJoZWxwZXJzJTIyJTNBJTVCJTVEJTdE)?
