### ISSUE TITLE
each helper breaks with no friendly error with Ember 3.3

### ISSUE THREAD

**Issue by kratiahuja** [glimmerjs/glimmer-vm#861]
With Ember 3.3, the glimmer-vm version was bumped to 0.35.4. However with that the following example breaks with no friendly error message:

```js
{{#each options as |option|}}
 ....
{{/each}}
```

Ofcourse if you read it, `option` is an HTML tag so Glimmer VM is crying but it doesn't throw a friendly error message. It simply throws `Error: unreachable` from [here](https://github.com/glimmerjs/glimmer-vm/blob/e30b3d64232a0972365c8cbb1dd8e236a0f33dcf/packages/%40glimmer/syntax/lib/generation/print.ts#L7) which isn't intuitive to understand.

Another example:

```js
{{#my-component as |p|}}
 ...
{{/my-component}}
```

Can we throw a better error message? It would significantly help readers understand their mistake. Ideally there should also be some kind of lint rule for the same.

**Comment by rwjblue** [comment]
Definitely a bug, see my write up in https://github.com/emberjs/ember.js/issues/16826#issuecomment-408504435 for some more details. In the mean time enabling the lint rule for `no-shadowed-elements` would give much better feedback to folks.

**Comment by kratiahuja** [comment]
Thanks Rob! I missed upgrading `ember-cli-template-lint` to the beta version which has this new rule in recommended. I'll go ahead and do that.

**Comment by kratiahuja** [comment]
Please feel free to close this. My apologies, I didn't realize there was an issue already open.

**Comment by kratiahuja** [comment]
Closing as this is resolved for me.
