### ISSUE TITLE
[@glimmer/opcode-compiler] error:  - Compile Error: c is not a helper 

### ISSUE THREAD

**Issue by lifeart** [glimmerjs/glimmer-vm#902]
https://ember-twiddle.com/9fe49dfa9d79376ad25e2e1f2f2e4452?openFiles=templates.components.my-component.hbs%2Ctemplates.components.my-component.hbs

**Comment by lifeart** [comment]
@rwjblue sorry, gist cleaned up, to get minimal reproduction.

if we somehow set Curried component into scope, we able to render it anyware, but, if we render it using `if` condition, we unable to add more params to Curried component.

**Comment by lifeart** [comment]
```hbs
<h1>{{appName}}</h1>
<br>

{{#let (component 'my-component' a=11 b=12) (component 'my-component' a=11 b=12) as |c someComponent|}}
rendered:
{{c}}

{{#if true}}
  rendered:
  {{component c a=12}}
{{/if}}

// rendered 
{{#if true}}
	<someComponent @a=12 />
{{/if}}

// throws  Compile Error: c is not a helper
{{#if true}}
	issued:
	{{c a=12}}
{{/if}}


{{/let}}

<br>
<br>
```

**Comment by chancancode** [comment]
this is fixed in the some recent version of Ember (changing the gist to use 3.8.0 fixed the issue)
