### ISSUE TITLE
Broken rerender on 1+ item removal for tacked by `@identity` lists

### ISSUE THREAD

**Issue by lifeart** [glimmerjs/glimmer-vm#934]
ref: http://tinyurl.com/y49yll8h
<details>
  <summary>Code sample</summary>

```ts
import Component, { tracked } from '@glimmer/component';

class Item {
  public id: string;
  @tracked public label: string;
  constructor({id, label}) {
    this.id = id;
    this.label = label;
  }
}

export default class extends Component {
  @tracked data: Item[] = [];
  remove(id) {
    this.data = this.data.filter(el=>el.id !== id);
  }
  didInsertElement() {
      setTimeout(()=>{
        this.createItems();
      });
  }
  createItems() {
    this.data = (new Array(10).fill(null)).map((el, index) => {
      return new Item({id: index, label: index});
    });
  }
}
```

```hbs

<button onclick={{action this.createItems}}>create Items</button>

<ul>
{{#each this.data key="@identity" as |item|}}
<li>{{item.label}} <button onclick={{action this.remove item.id}}>Remove</button></li>
{{/each}}
</ul>
```

</details>

How to reproduce?

click "remove" on 2 elements, 1 will be ok, second - will break rerender

for `key="@index"` all working `OK`

**Comment by lifeart** [comment]
also, looks like `@identity` logic don't work well for lists swapping.

given:
[ 1, 2, 3, 4, 5, 6 ]
2 -> 6, 6 -> 2
[ 1, 6, 3, 4, 5, 2 ]

produce full list rerender, instead of 2 items rerender.

ref: https://github.com/krausest/js-framework-benchmark/pull/554#issuecomment-487322072

**Comment by rwjblue** [comment]
Hmm, glimmer.js does not support `@identity` (that is an Ember feature). It supports the following "special" key values: `@primitive` and `@index`. Any other value is interpreted as a "path" on the object.

**Comment by lifeart** [comment]
@rwjblue is it possible to throw an error in glimmer-only environment?

**Comment by rwjblue** [comment]
Ya, tweak this:

https://github.com/glimmerjs/glimmer.js/blob/af7c10d3133820afa814aaf4e5dde28e96ccf99a/packages/%40glimmer/application/src/iterable.ts#L92

To check for `keyPath === '@identity'` and throw an error

**Comment by lifeart** [comment]
https://github.com/glimmerjs/glimmer.js/pull/190

**Comment by lifeart** [comment]
I think we can close it, asserts already in master
