### ISSUE TITLE
Ideas on initial list rendering / items additional optimizations

### ISSUE THREAD

**Issue by lifeart** [glimmerjs/glimmer-vm#947]
as I understand, we recreate whole elements during "each" loop first time rendering.
I suppose for "each" loops more complex case is -> clone prev loop item's DOM and run Updating programm on it.

	each loop (first time)
	
		create element li
		create element div
		create element a
		append text to a 		-> updating programm
		set attribute "href"	-> updating programm
		
	each loop (optimized?)
	
		if (!has 0 item reference) {
			create element li
			create element div
			create element a
			append text to a 		-> updating programm
			set attribute "href"	-> updating programm
		}
		
		for 1..n items
		
		- get first loop DOM reference, clone reference, run updating programm on it.
		

 optimization related to browser DOM API batching (cloning existing dom structure is more performant way, comparing building one)
 
 first time loop rendering using documentFragment may be an case too.

**Comment by lifeart** [comment]
perf proof: https://codepen.io/lifeart/pen/vwvJgJ

for simple list items perf almost same, but if we have 3-5 nodes in item, cloning has 25% perf improvement

https://codepen.io/lifeart/pen/vwvJgJ

**Comment by chancancode** [comment]
We used to do this, but if you need to walk the dom after it’s clones to get references to some of its child nodes, the engine then have to reify the C++ objects into js which makes it a wash or even slower sometimes.

**Comment by lifeart** [comment]
now I see weak points, thank you!
