### ISSUE TITLE
[@glimmer/syntax] Partial support

### ISSUE THREAD

**Issue by AndrewLeedham** [glimmerjs/glimmer-vm#948]
I noticed an error is thrown if a partial is found in a HBS file when parsing it with @glimmer/syntax. I can't find any documentation as to why it is not supported. Is this something that may come in the future, or is there a technical reason Partials aren't supported?

**Comment by lifeart** [comment]
It’s deprecated feature https://github.com/emberjs/rfcs/blob/master/text/0449-deprecate-partials.md

**Comment by AndrewLeedham** [comment]
Thanks @lifeart. For context I am trying to figure out a way of adding partial support to https://github.com/danakt/handlebars-to-jsx which currently uses `@glimmer/syntax` to create an AST.

**Comment by lifeart** [comment]
How `partials` will look like in `jsx` output?
Easy way - replace `{{partial..}}` beform transform to `{{jsx-partial..}}` and align final output

**Comment by rwjblue** [comment]
@lifeart I suspect that @andrewleedham is referring to the handlebars partial syntax, **not** Ember's `{{partial`. 

@andrewleedham - In general, @glimmer/syntax is specifically supporting Ember's style of Handlebars and as such we specifically error for syntax in Handlebars that Ember doesn't support.

**Comment by AndrewLeedham** [comment]
@rwjblue You are correct I am looking for both `{{>` and `{{#>` partial support. Seems like `@glimmer/syntax` isn't the right tool for the job. Thanks for your help 👍
