### ISSUE TITLE
Update to the latest TypeScript

### ISSUE THREAD

**Issue by pzuraq** [glimmerjs/glimmer-vm#965]
The perf work we did recently requires us to update to a more recent version of TS (`3.3.3`), and there are failures on the latest TS for some of our typings. It would probably be best to update and get the latest features, and fix the typing issues.

**Comment by Turbo87** [comment]
https://github.com/glimmerjs/glimmer-vm/pull/1053 updated TypeScript to the latest version, so I guess we can close this now
